/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AccountRewardsRouteImport } from './routes/account/rewards'
import { Route as AccountAppointmentsRouteImport } from './routes/account/appointments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRewardsRoute = AccountRewardsRouteImport.update({
  id: '/account/rewards',
  path: '/account/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAppointmentsRoute = AccountAppointmentsRouteImport.update({
  id: '/account/appointments',
  path: '/account/appointments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/account/appointments': typeof AccountAppointmentsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/account/appointments': typeof AccountAppointmentsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/account/appointments': typeof AccountAppointmentsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/services'
    | '/signup'
    | '/account/appointments'
    | '/account/rewards'
    | '/admin/appointments'
    | '/account'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/services'
    | '/signup'
    | '/account/appointments'
    | '/account/rewards'
    | '/admin/appointments'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/services'
    | '/signup'
    | '/account/appointments'
    | '/account/rewards'
    | '/admin/appointments'
    | '/account/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  AccountAppointmentsRoute: typeof AccountAppointmentsRoute
  AccountRewardsRoute: typeof AccountRewardsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/rewards': {
      id: '/account/rewards'
      path: '/account/rewards'
      fullPath: '/account/rewards'
      preLoaderRoute: typeof AccountRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/appointments': {
      id: '/account/appointments'
      path: '/account/appointments'
      fullPath: '/account/appointments'
      preLoaderRoute: typeof AccountAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  AccountAppointmentsRoute: AccountAppointmentsRoute,
  AccountRewardsRoute: AccountRewardsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
